import {
  siBehance,
  siBitbucket,
  siBitcoin,
  siBluesky,
  siCashapp,
  siCodepen,
  siCoinbase,
  siDiscord,
  siDocker,
  siDribbble,
  siEthereum,
  siFacebook,
  siFigma,
  siGithub,
  siGitlab,
  siGoogle,
  siInstagram,
  siKofi,
  siLightning,
  siLine,
  siLinktree,
  siMastodon,
  siMedium,
  siMessenger,
  siNotion,
  siNpm,
  siOpenai,
  siPatreon,
  siPaypal,
  siPinterest,
  siPnpm,
  siProducthunt,
  siReddit,
  siSlack,
  siSnapchat,
  siSolana,
  siSoundcloud,
  siSpotify,
  siStackoverflow,
  siStripe,
  siSubstack,
  siTelegram,
  siThreads,
  siTiktok,
  siTumblr,
  siTwitch,
  siVimeo,
  siWechat,
  siWhatsapp,
  siX,
  siYarn,
  siYoutube
} from "simple-icons";
import type { Component } from "solid-js";
import type { KnownSiteId } from "./known-sites-data";
import { createSimpleIcon, IconLinkedin, IconSkype, IconTwitter, IconWallet } from "./custom-icons";

export type KnownSiteIconComponent = Component<Record<string, unknown>>;

const knownSiteIcons: Record<KnownSiteId, KnownSiteIconComponent> = {
  github: createSimpleIcon(siGithub),
  linkedin: IconLinkedin,
  x: createSimpleIcon(siX),
  twitter: IconTwitter,
  youtube: createSimpleIcon(siYoutube),
  instagram: createSimpleIcon(siInstagram),
  facebook: createSimpleIcon(siFacebook),
  tiktok: createSimpleIcon(siTiktok),
  reddit: createSimpleIcon(siReddit),
  discord: createSimpleIcon(siDiscord),
  threads: createSimpleIcon(siThreads),
  bluesky: createSimpleIcon(siBluesky),
  mastodon: createSimpleIcon(siMastodon),
  twitch: createSimpleIcon(siTwitch),
  snapchat: createSimpleIcon(siSnapchat),
  pinterest: createSimpleIcon(siPinterest),
  tumblr: createSimpleIcon(siTumblr),
  vimeo: createSimpleIcon(siVimeo),
  spotify: createSimpleIcon(siSpotify),
  soundcloud: createSimpleIcon(siSoundcloud),
  telegram: createSimpleIcon(siTelegram),
  whatsapp: createSimpleIcon(siWhatsapp),
  wechat: createSimpleIcon(siWechat),
  line: createSimpleIcon(siLine),
  messenger: createSimpleIcon(siMessenger),
  skype: IconSkype,
  slack: createSimpleIcon(siSlack),
  gitlab: createSimpleIcon(siGitlab),
  bitbucket: createSimpleIcon(siBitbucket),
  stackoverflow: createSimpleIcon(siStackoverflow),
  codepen: createSimpleIcon(siCodepen),
  producthunt: createSimpleIcon(siProducthunt),
  dribbble: createSimpleIcon(siDribbble),
  behance: createSimpleIcon(siBehance),
  figma: createSimpleIcon(siFigma),
  medium: createSimpleIcon(siMedium),
  notion: createSimpleIcon(siNotion),
  npm: createSimpleIcon(siNpm),
  pnpm: createSimpleIcon(siPnpm),
  yarn: createSimpleIcon(siYarn),
  docker: createSimpleIcon(siDocker),
  linktree: createSimpleIcon(siLinktree),
  patreon: createSimpleIcon(siPatreon),
  kofi: createSimpleIcon(siKofi),
  paypal: createSimpleIcon(siPaypal),
  cashapp: createSimpleIcon(siCashapp),
  stripe: createSimpleIcon(siStripe),
  coinbase: createSimpleIcon(siCoinbase),
  bitcoin: createSimpleIcon(siBitcoin),
  lightning: createSimpleIcon(siLightning),
  ethereum: createSimpleIcon(siEthereum),
  solana: createSimpleIcon(siSolana),
  wallet: IconWallet,
  substack: createSimpleIcon(siSubstack),
  google: createSimpleIcon(siGoogle),
  openai: createSimpleIcon(siOpenai)
};

export const resolveKnownSiteIcon = (siteId: KnownSiteId): KnownSiteIconComponent => knownSiteIcons[siteId];
