import {
  IconBrandBehance,
  IconBrandBitbucketFilled,
  IconBrandBluesky,
  IconBrandCodepen,
  IconBrandDiscordFilled,
  IconBrandDocker,
  IconBrandDribbbleFilled,
  IconBrandFacebookFilled,
  IconBrandFigma,
  IconBrandGithubFilled,
  IconBrandGitlab,
  IconBrandGoogleFilled,
  IconBrandInstagramFilled,
  IconBrandLine,
  IconBrandLinkedinFilled,
  IconBrandLinktree,
  IconBrandMastodon,
  IconBrandMedium,
  IconBrandMessengerFilled,
  IconBrandNotion,
  IconBrandNpm,
  IconBrandOpenai,
  IconBrandPatreonFilled,
  IconBrandPinterestFilled,
  IconBrandPnpm,
  IconBrandProducthunt,
  IconBrandReddit,
  IconBrandSkype,
  IconBrandSlack,
  IconBrandSnapchatFilled,
  IconBrandSoundcloud,
  IconBrandSpotifyFilled,
  IconBrandStackoverflow,
  IconBrandTelegram,
  IconBrandThreads,
  IconBrandTiktokFilled,
  IconBrandTumblrFilled,
  IconBrandTwitch,
  IconBrandTwitterFilled,
  IconBrandVimeoFilled,
  IconBrandWechat,
  IconBrandWhatsappFilled,
  IconBrandXFilled,
  IconBrandYarn,
  IconBrandYoutubeFilled
} from "@tabler/icons-solidjs";
import type { Component } from "solid-js";
import type { KnownSiteId } from "./known-sites-data";

export type KnownSiteIconComponent = Component<Record<string, unknown>>;

const knownSiteIcons: Record<KnownSiteId, KnownSiteIconComponent> = {
  github: IconBrandGithubFilled,
  linkedin: IconBrandLinkedinFilled,
  x: IconBrandXFilled,
  twitter: IconBrandTwitterFilled,
  youtube: IconBrandYoutubeFilled,
  instagram: IconBrandInstagramFilled,
  facebook: IconBrandFacebookFilled,
  tiktok: IconBrandTiktokFilled,
  reddit: IconBrandReddit,
  discord: IconBrandDiscordFilled,
  threads: IconBrandThreads,
  bluesky: IconBrandBluesky,
  mastodon: IconBrandMastodon,
  twitch: IconBrandTwitch,
  snapchat: IconBrandSnapchatFilled,
  pinterest: IconBrandPinterestFilled,
  tumblr: IconBrandTumblrFilled,
  vimeo: IconBrandVimeoFilled,
  spotify: IconBrandSpotifyFilled,
  soundcloud: IconBrandSoundcloud,
  telegram: IconBrandTelegram,
  whatsapp: IconBrandWhatsappFilled,
  wechat: IconBrandWechat,
  line: IconBrandLine,
  messenger: IconBrandMessengerFilled,
  skype: IconBrandSkype,
  slack: IconBrandSlack,
  gitlab: IconBrandGitlab,
  bitbucket: IconBrandBitbucketFilled,
  stackoverflow: IconBrandStackoverflow,
  codepen: IconBrandCodepen,
  producthunt: IconBrandProducthunt,
  dribbble: IconBrandDribbbleFilled,
  behance: IconBrandBehance,
  figma: IconBrandFigma,
  medium: IconBrandMedium,
  notion: IconBrandNotion,
  npm: IconBrandNpm,
  pnpm: IconBrandPnpm,
  yarn: IconBrandYarn,
  docker: IconBrandDocker,
  linktree: IconBrandLinktree,
  patreon: IconBrandPatreonFilled,
  google: IconBrandGoogleFilled,
  openai: IconBrandOpenai
};

export const resolveKnownSiteIcon = (siteId: KnownSiteId): KnownSiteIconComponent => knownSiteIcons[siteId];
