export const GITHUB_HOSTS = new Set(["github.com", "gist.github.com"]);
export const X_HOSTS = new Set(["x.com", "twitter.com", "mobile.twitter.com"]);
export const LINKEDIN_HOSTS = new Set(["linkedin.com", "lnkd.in"]);
export const FACEBOOK_HOSTS = new Set(["facebook.com", "m.facebook.com", "fb.com"]);
export const INSTAGRAM_HOSTS = new Set(["instagram.com"]);
export const CLUB_ORANGE_DOMAIN = "cluborange.org";
export const RUMBLE_HOSTS = new Set(["rumble.com"]);
export const PRIMAL_HOSTS = new Set(["primal.net"]);
export const MEDIUM_HOSTS = new Set(["medium.com"]);
export const SUBSTACK_HOSTS = new Set(["substack.com"]);
export const YOUTUBE_HOSTS = new Set(["youtube.com", "m.youtube.com", "youtu.be"]);

export const GITHUB_RESERVED = new Set([
  "about",
  "account",
  "apps",
  "blog",
  "collections",
  "contact",
  "dashboard",
  "enterprise",
  "events",
  "explore",
  "features",
  "gist",
  "gist.github.com",
  "issues",
  "login",
  "logout",
  "marketplace",
  "new",
  "notifications",
  "organizations",
  "orgs",
  "pricing",
  "pulls",
  "readme",
  "search",
  "security",
  "settings",
  "signup",
  "site",
  "sponsors",
  "team",
  "topics",
  "trending",
  "users",
]);

export const X_RESERVED = new Set([
  "about",
  "compose",
  "explore",
  "hashtag",
  "home",
  "i",
  "intent",
  "login",
  "messages",
  "notifications",
  "privacy",
  "search",
  "settings",
  "share",
  "signup",
  "tos",
]);

export const FACEBOOK_RESERVED = new Set([
  "about",
  "accounts",
  "adsmanager",
  "business",
  "events",
  "friends",
  "gaming",
  "groups",
  "help",
  "home.php",
  "login",
  "marketplace",
  "messages",
  "notifications",
  "pages",
  "people",
  "photo.php",
  "photos",
  "plugins",
  "privacy",
  "profile.php",
  "reel",
  "reels",
  "search",
  "settings",
  "share",
  "stories",
  "story.php",
  "watch",
]);

export const INSTAGRAM_RESERVED = new Set([
  "about",
  "accounts",
  "api",
  "challenge",
  "developer",
  "direct",
  "explore",
  "legal",
  "p",
  "press",
  "privacy",
  "reel",
  "reels",
  "stories",
  "tv",
  "web",
]);

export const PRIMAL_RESERVED = new Set([
  "about",
  "bookmarks",
  "downloads",
  "explore",
  "home",
  "login",
  "messages",
  "notifications",
  "premium",
  "search",
  "settings",
  "signup",
  "wallet",
]);

export const RUMBLE_RESERVED = new Set([
  "about",
  "account",
  "ads",
  "c",
  "categories",
  "channel",
  "channels",
  "contact-us",
  "embed",
  "help",
  "live",
  "login",
  "logout",
  "news",
  "our-picks",
  "privacy",
  "search",
  "settings",
  "terms",
  "user",
  "video",
  "videos",
]);

export const RUMBLE_PROFILE_TABS = new Set([
  "about",
  "channels",
  "livestreams",
  "reposts",
  "videos",
]);

export const CLUB_ORANGE_RESERVED = new Set([
  "about",
  "admin",
  "app",
  "community",
  "download",
  "events",
  "groups",
  "home",
  "login",
  "messages",
  "notifications",
  "privacy",
  "settings",
  "signup",
  "terms",
  "user",
  "wallet",
]);

export const MEDIUM_RESERVED = new Set([
  "about",
  "creators",
  "m",
  "me",
  "membership",
  "notifications",
  "plans",
  "policy",
  "privacy",
  "publish",
  "p",
  "search",
  "signin",
  "signup",
  "tag",
  "topics",
  "write",
]);

export const SUBSTACK_SUBDOMAIN_RESERVED = new Set([
  "api",
  "app",
  "cdn",
  "help",
  "podcasts",
  "profile",
  "static",
  "substack",
  "support",
  "www",
]);

export const YOUTUBE_RESERVED = new Set([
  "about",
  "account",
  "feed",
  "gaming",
  "hashtag",
  "jobs",
  "kids",
  "live",
  "music",
  "news",
  "playlist",
  "premium",
  "results",
  "shorts",
  "watch",
]);

export const LINKEDIN_PREFIXES = new Set(["in", "company", "school"]);
